// app/terms/page.tsx

import { Separator } from "@/components/ui/separator";

export default function TermsPage() {
  return (
    <main className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <div className="space-y-6">
        <h1 className="text-3xl font-bold tracking-tight text-blue-600">
          Terms and Conditions
        </h1>
        <Separator />
        <div className="prose prose-gray max-w-none">
          <p>
            <strong>Last updated:</strong> 25 May 2025
          </p>

          <h2>1. Introduction</h2>
          <p>
            By using Second Brain, you agree to abide by these terms and our
            Privacy Policy. If you do not agree, please discontinue use of our
            services.
          </p>

          <h2>2. Data Usage</h2>
          <p>
            Your memories are securely stored and used solely to improve the AI
            experience for you.
          </p>

          <h2>3. AI Limitations</h2>
          <p>
            Responses generated by our AI may not always be accurate or
            complete. Use discretion before acting on them.
          </p>

          <h2>4. Changes to Terms</h2>
          <p>
            We may update our terms from time to time. Continued use of the
            service implies acceptance of updated terms.
          </p>

          <h2>5. Contact</h2>
          <p>
            If you have questions or concerns, contact us at{" "}
            <a href="mailto:support@secondbrain.ai">support@secondbrain.ai</a>.
          </p>
        </div>
      </div>
    </main>
  );
}
